apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: longhorn-cert
spec:
  commonName: "longhorn.k8s.nickolaj.com"
  secretName: longhorn-cert
  dnsNames:
    - "longhorn.k8s.nickolaj.com"
  issuerRef:
    name: letsencrypt # it's a precreated clusterissuer name, can also be "letsencrypt-staging" for testing.
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn.k8s.nickolaj.com`)
      kind: Rule
      middlewares:
      - name: traefik-forwardauth
      services:
        - name: longhorn-frontend
          port: 80
  tls:
    secretName: longhorn-cert