apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key-secret
  annotations:
    avp.kubernetes.io/path: "kv/data/cert-manager/cloudflare/"
type: Opaque
stringData:
  api-token: <api-key>
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: nickolaj1177@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    solvers:
    - dns01:
        ingress:
          cloudflare:
            email: nickolaj1177@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: nickolaj1177@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt
    # Enable the HTTP-01 challenge provider
    solvers:
    - dns01:
        ingress:
          cloudflare:
            email: nickolaj1177@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
