apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  annotations:
    avp.kubernetes.io/path: "kv/data/fortnite/postgres"
stringData:
  password: <password>
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: fortnite
            - name: POSTGRES_USER
              value: fortnite
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "postgres"
      volumes:
          name: postgres-volume
          storageClassName: longhorn
          resources:
            requests:
              storage: 10Gi
      