keycloak:
   extraEnv: |
      - name: PROXY_ADDRESS_FORWARDING
        value: "true"
      - name: KEYCLOAK_HTTP_PORT
        value: "80"
      - name: KEYCLOAK_HTTPS_PORT
        value: "443"
      - name: KEYCLOAK_HOSTNAME
        value: keycloak.k8s.nickolaj.com:8443
      - name: KEYCLOAK_FRONTEND_URL
        value: https://keycloak.k8s.nickolaj.com:8443/auth
      - name: KEYCLOAK_LOGLEVEL
        value: DEBUG
      - name: WILDFLY_LOGLEVEL
        value: DEBUG
      - name: CACHE_OWNERS_COUNT
        value: "2"
      - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
        value: "2"
traefik-forward-auth:
  default:
    provider: oidc
  providers:
    oidc:
      enabled: "true"
      issuerUrl: http://keycloak-http.keycloak/auth/realms/master/.well-known/openid-configuration
      clientId: traefik
      clientSecret: cb8cf02f-192c-473e-a5b1-cd2aa9d5ca46