keycloak:
   extraEnv: |
      - name: PROXY_ADDRESS_FORWARDING
        value: "true"
      - name: KEYCLOAK_HTTP_PORT
        value: "80"
      - name: KEYCLOAK_HTTPS_PORT
        value: "443"
      - name: KEYCLOAK_HOSTNAME
        value: keycloak.k8s.nickolaj.com:8443
      - name: KEYCLOAK_FRONTEND_URL
        value: https://keycloak.k8s.nickolaj.com:8443/auth
      - name: KEYCLOAK_LOGLEVEL
        value: DEBUG
      - name: WILDFLY_LOGLEVEL
        value: DEBUG
      - name: CACHE_OWNERS_COUNT
        value: "2"
      - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
        value: "2"
traefik-forward-auth:
  default:
    provider: oidc
  cookie:
    domain: k8s.nickolaj.com
  providers:
    oidc:
      enabled: "true"
  envFrom:
    - secretRef:
      name: keycloak-oidc-secret
