kube-prometheus-stack:
  grafana:
    enabled: true
    plugins:
    - grafana-piechart-panel
    persistence:
      enabled: true
      storageClassName: longhorn
      size: 10Gi
      accessModes:
        - ReadWriteOnce