traefik:
  ports:
    web:
      exposedPort: 8000
    websecure:
      exposedPort: 8443
    metrics:
      exposedPort: 9101
      expose: true
  additionalArguments:
    - "--metrics.prometheus=true"
    - "--authSources.oidcSource.oidc.issuer=https://keycloak.k8s.nickolaj.com:8443/auth/realms/master/.well-known/openid-configuration"
    - "--authSources.oidcSource.oidc.clientID=traefik"