traefik:
  ports:
    web:
      exposedPort: 8000
    websecure:
      exposedPort: 8443
    metrics:
      exposedPort: 9101
      expose: true
  additionalArguments:
    - "--metrics.prometheus=true"