apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fortnite
  namespace: argocd
spec:
  destination:
    namespace: fortnite
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/fortnite
    repoURL: git@github.com:nickolaj-jepsen/homelab
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin
  syncPolicy:
    syncOptions:
    - CreateNamespace=true