apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  destination:
    namespace: longhorn
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/longhorn
    repoURL: git@github.com:nickolaj-jepsen/homelab
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm
  syncPolicy:
    syncOptions:
    - CreateNamespace=true