apiVersion: v1
data:
  name: bG9uZ2hvcm4=
  type: aGVsbQ==
  url: aHR0cHM6Ly9jaGFydHMubG9uZ2hvcm4uaW8=
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-longhorn
  namespace: argocd
