apiVersion: v1
kind: Secret
metadata:
  name: keycloak-oidc-secret
  annotations:
    avp.kubernetes.io/path: "kv/data/keycloak/traefik-forward-auth/"
type: Opaque
stringData:
  PROVIDERS_OIDC_ISSUER_URL: <issuer-url>
  PROVIDERS_OIDC_CLIENT_ID: <client-id>
  PROVIDERS_OIDC_CLIENT_SECRET: <client-secret>
