apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monero-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 150Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monero
  labels:
    app: monero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monero
  template:
    metadata:
      labels:
        app: monero
    spec:
      containers:
      - name: monero
        image: varnav/monero
        ports:
        - name: node
          containerPort: 18080
        - name: rpc
          containerPort: 18081
        resources:
          limits:
            memory: "4Gi"
            cpu: "200m"
        volumeMounts:
          - name: monero-data
            mountPath: /home/monero/
      # initContainers:
      # - name: init-ulimitn
      #   image: busybox
      #   command: ["sh", "-c", "ulimit -n 16000"]
      #   securityContext:
      #     privileged: true
      volumes:
      - name: monero-data
        persistentVolumeClaim:
          claimName: monero-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: monero
spec:
  type: ClusterIP
  # Uncomment the below line to create a Headless Service
  # clusterIP: None
  selector:
    app: monero
  ports:
  - protocol: TCP
    port: 18080
    targetPort: 18080
  - protocol: TCP
    port: 18081
    targetPort: 18081