apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-deployment
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'git@github.com:nickolaj-jepsen/homelab.git'
    path: deployment
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'