apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik-pod-monitor
  namespace: prometheus-operator
spec:
  namespaceSelector:
    matchNames:
      - traefik
  endpoints:
  - port: traefik
    path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik
      app.kubernetes.io/name: traefik-dashboard