apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: traefik-pod-monitor
spec:
  jobLabel: traefik-metrics
  namespaceSelector:
    matchNames:
      - traefik
  endpoints:
  - port: traefik
    path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik
      app.kubernetes.io/name: traefik-dashboard