apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik-pod-monitor
  namespace: prometheus-operator
  labels:
    release: prometheus-operator
spec:
  namespaceSelector:
    matchNames:
      - traefik
  endpoints:
  - port: 9100
    path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik
      app.kubernetes.io/name: traefik