# dashboard.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
  annotations:
    avp.kubernetes.io/path: "kv/data/cert-manager/cloudflare/"
type: Opaque
stringData:
  api-token: <api-key>
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: traefik-cert
spec:
  commonName: "traefik.k8s.nickolaj.com"
  secretName: traefik-cert
  dnsNames:
    - "traefik.k8s.nickolaj.com"
  issuerRef:
    name: letsencrypt # it's a precreated clusterissuer name, can also be "letsencrypt-staging" for testing.
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.k8s.nickolaj.com`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      middlewares:
      - name: traefik-basic-auth
      services:
        - name: api@internal
          kind: TraefikService
  tls:
    secretName: traefik-cert